export const categories=[['Armchair','Furniture','1,248'],['Bike','Bicycles','863'],['Smartphone','Mobiles','2,104'],['Laptop','Laptops','945'],['Camera','Cameras','576'],['Palette','Arts & Music','728'],['Watch','Vintage','514'],['Gamepad2','Sports','738'],['WashingMachine','Appliances','611'],['Gem','Collectibles','319']];
export const listings=[
 {id:'sofa',title:'Mid-century olive sofa',category:'Furniture',location:'Brooklyn, NY',condition:'Gently used',exchange:'Coffee table or lounge chair',date:'Today',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80',desc:'A beautifully kept three-seat sofa in deep olive green. Solid walnut legs, firm cushions, and no stains. It has been the heart of our living room and deserves a great next home.'},
 {id:'bike',title:'Trek FX 3 Disc',category:'Bicycles',location:'Queens, NY',condition:'Like new',exchange:'Road bike',date:'Yesterday',image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80',desc:'Lightweight hybrid bike, recently serviced and ready to ride.'},
 {id:'speaker',title:'Sonos One speaker',category:'Electronics',location:'Manhattan, NY',condition:'Excellent',exchange:'Headphones',date:'2 days ago',image:'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80',desc:'Room-filling smart speaker in matte black with its original cable.'},
 {id:'table',title:'Solid oak dining table',category:'Furniture',location:'Brooklyn, NY',condition:'Good',exchange:'Armchair',date:'3 days ago',image:'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=900&q=80',desc:'Hand-finished table for six with beautiful natural grain.'},
 {id:'camera',title:'Canon AE-1 film camera',category:'Cameras',location:'Queens, NY',condition:'Excellent',exchange:'35mm lens',date:'4 days ago',image:'https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=900&q=80',desc:'Classic analog camera, fully tested with a clean viewfinder.'},
 {id:'plant',title:'Large monstera deliciosa',category:'Home & Garden',location:'Brooklyn, NY',condition:'Thriving',exchange:'Snake plant',date:'5 days ago',image:'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80',desc:'Healthy mature plant with a simple terracotta pot included.'},
 {id:'guitar',title:'Vintage acoustic guitar',category:'Arts & Music',location:'Jersey City, NJ',condition:'Good',exchange:'Turntable or records',date:'6 days ago',image:'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=80',desc:'Warm-toned acoustic guitar with a beautifully aged finish and a soft carrying case.'},
 {id:'typewriter',title:'1960s Olivetti typewriter',category:'Vintage',location:'Hoboken, NJ',condition:'Working',exchange:'Film camera or desk lamp',date:'1 week ago',image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80',desc:'A characterful manual typewriter in working order, complete with its original case.'}
];
export const offers=[{item:'Canon AE-1 film camera',offered:'Sony WH-1000XM4',user:'Maya R.',date:'Aug 18',status:'Pending'},{item:'Mid-century olive sofa',offered:'Oak coffee table',user:'Jon Bell',date:'Aug 16',status:'Accepted'},{item:'Trek FX 3 Disc',offered:'Fender acoustic guitar',user:'Anna K.',date:'Aug 12',status:'Rejected'}];
